app = "gamestore-unique123-lingering-pine-4132"

[build]
  builder = "heroku/buildpacks:20"
dockerfile = "Dockerfile"
  
[env]
PORT = "8080"

[[services]]
internal_port = 8080
external_port = 8080
processes = ["app"]
protocol = "tcp"
script_checks = []

[services.concurrency]
type = "requests"
soft_limit = 25
hard_limit = 50

[[services.ports]]
port = 80
handlers = ["http"]

[http_service]
internal_port = 8080
force_https = true
