app = "gamestore-unique123-lingering-pine-4132"

[env]
DATABASE_HOST = "gamestoretp.internal"
DATABASE_NAME = "postgres"
DATABASE_USER = "postgres"
DATABASE8_PORT = "5432"

[build]
dockerfile = "Dockerfile"

[mounts]
source="gamestore_assets"
destination="/app/asset"

[http_service]
internal_port = 80
force_https = true

[[services]]
http_checks = []
internal_port = 80
processes = ["app"]
protocol = "tcp"
script_checks = []

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443